name: Runners

on:
  push:
    branches:
      - 'main'
    paths:
      - 'runner/VERSION'
      - '.github/workflows/release-runners.yaml'

env:
  PUSH_TO_REGISTRIES: true
  TARGET_ORG: rpenziol
  TARGET_REPO: gitea-actions-runner
  DOCKER_VERSION: 20.10.23

jobs:
  build-runners:
    name: Trigger Build and Push of Runner Images
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gitea-actions-runner
            os-name: ubuntu
            os-version: 20.04
            latest: "false"
          - name: gitea-actions-runner
            os-name: ubuntu
            os-version: 22.04
            latest: "true"
          - name: gitea-actions-runner-dind
            os-name: ubuntu
            os-version: 20.04
            latest: "false"
          - name: gitea-actions-runner-dind
            os-name: ubuntu
            os-version: 22.04
            latest: "true"
          - name: gitea-actions-runner-dind-rootless
            os-name: ubuntu
            os-version: 20.04
            latest: "false"
          - name: gitea-actions-runner-dind-rootless
            os-name: ubuntu
            os-version: 22.04
            latest: "true"

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.TARGET_ORG }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Export env vars
        run: |
            echo "SHA_SHORT=$(git -C $GITHUB_WORKSPACE rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "LATEST_TAG_GHCR=ghcr.io/${{ env.TARGET_ORG }}/${{ env.TARGET_REPO }}/${{ matrix.name }}:latest" >> $GITHUB_ENV

      - name: Build and Push Versioned Tags
        uses: docker/build-push-action@v4
        with:
          context: ./runner
          file: ./runner/${{ matrix.name }}.${{ matrix.os-name }}-${{ matrix.os-version }}.dockerfile
          platforms: linux/amd64
          push: ${{ env.PUSH_TO_REGISTRIES }}
          build-args: |
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
          tags: |
            ghcr.io/${{ env.TARGET_ORG }}/${{ env.TARGET_REPO }}/${{ matrix.name }}:${{ matrix.os-name }}-${{ matrix.os-version }}
            ghcr.io/${{ env.TARGET_ORG }}/${{ env.TARGET_REPO }}/${{ matrix.name }}:${{ matrix.os-name }}-${{ matrix.os-version }}-${{ env.SHA_SHORT }}
            ${{ matrix.latest == 'true' && env.LATEST_TAG_GHCR || '' }}
