name: Runners

on:
  push:
    branches:
      - 'main'
    paths:
      - 'runner/VERSION'
      - '.github/workflows/release-runners.yaml'

env:
  PUSH_TO_REGISTRIES: true
  TARGET_ORG: rpenziol
  DOCKER_VERSION: 20.10.23
  RUNNER_CONTAINER_HOOKS_VERSION: 0.2.0

jobs:
  build-runners:
    name: Trigger Build and Push of Runner Images
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gitea-actions-runner
            os-name: ubuntu
            os-version: 20.04
            latest: "true"
          - name: gitea-actions-runner
            os-name: ubuntu
            os-version: 22.04
            latest: "false"
          - name: gitea-actions-runner-dind
            os-name: ubuntu
            os-version: 20.04
            latest: "true"
          - name: gitea-actions-runner-dind
            os-name: ubuntu
            os-version: 22.04
            latest: "false"
          - name: gitea-actions-runner-dind-rootless
            os-name: ubuntu
            os-version: 20.04
            latest: "true"
          - name: gitea-actions-runner-dind-rootless
            os-name: ubuntu
            os-version: 22.04
            latest: "false"

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.TARGET_ORG }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and Push Versioned Tags
        uses: docker/build-push-action@v4
        with:
          context: ./runner
          file: ./runner/${{ matrix.name }}.${{ matrix.os-name }}-${{ matrix.os-version }}.dockerfile
          push: ${{ env.PUSH_TO_REGISTRIES }}
          build-args: |
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
            RUNNER_CONTAINER_HOOKS_VERSION=${{ env.RUNNER_CONTAINER_HOOKS_VERSION }}
          tags: |
            ghcr.io/${{ env.TARGET_ORG }}/${{ matrix.name }}:${{ matrix.os-name }}-${{ matrix.os-version }}
